# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30, verbose_name='姓名')),
                ('address', models.CharField(max_length=20, verbose_name='宿舍号')),
                ('phone', models.CharField(max_length=10, verbose_name='联系方式')),
                ('grade', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='express.Grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '毕业生',
                'verbose_name_plural': '毕业生',
            },
        ),
    ]
