# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_auto_20190519_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='宿舍号')),
            ],
            options={
                'verbose_name': '宿舍',
                'verbose_name_plural': '宿舍',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='ctime',
            field=models.CharField(choices=[('1', '上午'), ('2', '下午')], default='1', max_length=3, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=20, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 22, 12, 23, 32, 387211, tzinfo=utc), verbose_name='预定日期'),
        ),
        migrations.AddField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='express.Dormitory', verbose_name='宿舍号'),
        ),
    ]
