# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='手机号')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='地址')),
                ('nick', models.CharField(blank=True, default='', max_length=50, verbose_name='称号')),
                ('count', models.CharField(blank=True, default='', max_length=50, verbose_name='获奖数')),
            ],
            options={
                'verbose_name': '答题抽奖',
                'verbose_name_plural': '答题抽奖',
            },
        ),
    ]
