# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_clickmap_clickmaparea_clickmapaward_clickmapawardcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickmap',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='二次未中提示语'),
        ),
        migrations.AlterField(
            model_name='clickmap',
            name='img',
            field=models.ImageField(blank=True, upload_to='clickmap', verbose_name='抽奖图片'),
        ),
        migrations.AlterField(
            model_name='clickmap',
            name='url',
            field=models.CharField(blank=True, max_length=50, verbose_name='抽奖链接'),
        ),
    ]
