# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20190507_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickmap',
            name='img',
            field=models.FileField(blank=True, upload_to='clickmap', verbose_name='抽奖图片'),
        ),
    ]
