# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20190507_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickmapaward',
            name='rate',
            field=models.FloatField(default=0, verbose_name='奖品概率'),
        ),
        migrations.AlterField(
            model_name='clickmapawardcode',
            name='use',
            field=models.CharField(choices=[('1', '未使用'), ('2', '已使用')], default='1', max_length=2, verbose_name='使用情况'),
        ),
    ]
