# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20190508_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickMapAreaAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0, verbose_name='奖品概率')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.ClickMapArea', verbose_name='绑定区域')),
            ],
            options={
                'verbose_name': '奖品指定',
                'verbose_name_plural': '奖品指定',
            },
        ),
        migrations.AlterModelOptions(
            name='clickmapaward',
            options={'verbose_name': '抽奖奖品', 'verbose_name_plural': '抽奖奖品'},
        ),
        migrations.RemoveField(
            model_name='clickmapaward',
            name='area',
        ),
        migrations.RemoveField(
            model_name='clickmapaward',
            name='rate',
        ),
        migrations.AddField(
            model_name='clickmapaward',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='clickmapaward',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='clickmapareaaward',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.ClickMapAward', verbose_name='绑定奖品'),
        ),
    ]
