# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20190509_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='解锁码')),
            ],
            options={
                'verbose_name': '解锁码',
                'verbose_name_plural': '解锁码',
            },
        ),
    ]
